apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: wordpress

commonAnnotations:
  maintainer: mglynn@amazon.com
namePrefix: kustomize-
namespace: wordpress-kustomize

vars:
  - name: MYSQL_WORDPRESS_DB_HOST
    objref:
      kind: Service
      name: wordpress-mysql
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name

resources:
- ./tier/mysql
- ./tier/frontend
