apiVersion: v1
data:
  database: wordpress
kind: ConfigMap
metadata:
  annotations:
    maintainer: mglynn@amazon.com
  labels:
    app: wordpress
    tier: mysql
  name: kustomize-wordpress-config-mddtd45m58
  namespace: wordpress-kustomize
---
apiVersion: v1
data:
  password: bXlwYXNzd2Q=
  username: bXl1c2Vy
kind: Secret
metadata:
  annotations:
    maintainer: mglynn@amazon.com
  labels:
    app: wordpress
    tier: mysql
  name: kustomize-wordpress-db-secret-bhkb6ctf49
  namespace: wordpress-kustomize
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    maintainer: mglynn@amazon.com
  labels:
    app: wordpress
    tier: frontend
  name: kustomize-wordpress
  namespace: wordpress-kustomize
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    maintainer: mglynn@amazon.com
  labels:
    app: wordpress
    tier: mysql
  name: kustomize-wordpress-mysql
  namespace: wordpress-kustomize
spec:
  ports:
  - port: 3306
  selector:
    app: wordpress
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    maintainer: mglynn@amazon.com
  labels:
    app: wordpress
    tier: mysql
  name: kustomize-mysql-pv-claim
  namespace: wordpress-kustomize
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    maintainer: mglynn@amazon.com
  labels:
    app: wordpress
    tier: frontend
  name: kustomize-wordpress
  namespace: wordpress-kustomize
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        maintainer: mglynn@amazon.com
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: kustomize-wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: kustomize-wordpress-db-secret-bhkb6ctf49
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: kustomize-wordpress-db-secret-bhkb6ctf49
        image: 987210092513.dkr.ecr.us-east-1.amazonaws.com/eks-demo-wordpress:latest
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    maintainer: mglynn@amazon.com
  labels:
    app: wordpress
    tier: mysql
  name: kustomize-wordpress-mysql
  namespace: wordpress-kustomize
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        maintainer: mglynn@amazon.com
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: kustomize-wordpress-db-secret-bhkb6ctf49
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: kustomize-wordpress-db-secret-bhkb6ctf49
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: kustomize-wordpress-db-secret-bhkb6ctf49
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: database
              name: kustomize-wordpress-config-mddtd45m58
        image: public.ecr.aws/u3e9a9s8/eks-demo-mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: kustomize-mysql-pv-claim
