apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  tier: mysql
  
configMapGenerator:
- name: wordpress-config
  literals:
  - database=wordpress
secretGenerator:
- name: wordpress-db-secret
  literals:
  - password=mypasswd
  - username=myuser

resources:
- wordpress-mysql-deployment.yaml
- wordpress-mysql-svc.yaml
- wordpress-mysql-pvc.yaml
