apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - image: 987210092513.dkr.ecr.us-east-1.amazonaws.com/mglab-wordpress-kustomize-argocd:588836e1
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: $(MYSQL_WORDPRESS_DB_HOST)
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: password
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: username
        ports:
        - containerPort: 80
          name: wordpress
